[package]
name = "pid-allocator"
version = "0.1.0"
edition = "2021"
authors = ["Kiritan <kiritantakechi@gmail.com>"]
keywords = ["allocator", "pid"]
categories = ["no-std"]
readme = "README.md"
license = "MIT"

[profile.release]
opt-level = 3
lto = true

[dependencies]
spin = "0.9.0"
